url: https://status.brandoriented.pl
author: BrandOriented
email: support@brandoriented.pl
title: BrandOriented Status
description: The status page for the BrandOriented services
homepage: https://brandoriented.pl

permalink: pretty
uptime_days: 60

# TODO: Build pagination into archive
gems: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
